name: Build Swift Binary

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Swift
        run: |
          brew install swift

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # 创建临时 keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain

          # 导入证书到 keychain
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # 导入 provisioning profile
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output profile.provisionprofile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.provisionprofile ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Create entitlements
        run: |
          cat > entitlements.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.security.app-sandbox</key>
              <true/>
              
              <!-- 添加您需要的其他权限 -->
          </dict>
          </plist>
          EOF

      - name: Build Swift Script
        run: |
          # x86_64 版本
          xcrun swiftc -target x86_64-apple-macos10.15 \
            -sdk $(xcrun --show-sdk-path) \
            -profile ~/Library/MobileDevice/Provisioning\ Profiles/profile.provisionprofile \
            -sign "Developer ID Application: YOUR NAME" \
            -entitlements entitlements.plist \
            -o ocr-x86_64-apple-darwin main.swift

          # arm64 版本
          xcrun swiftc -target arm64-apple-macos11 \
            -sdk $(xcrun --show-sdk-path) \
            -profile ~/Library/MobileDevice/Provisioning\ Profiles/profile.provisionprofile \
            -sign "Developer ID Application: YOUR NAME" \
            -entitlements entitlements.plist \
            -o ocr-aarch64-apple-darwin main.swift

      - name: Test
        run: ./ocr-x86_64-apple-darwin $(pwd)/test.jpg auto

      - name: Upload x86_64 Binary
        uses: actions/upload-artifact@v3
        with:
          name: ocr-x86_64-apple-darwin
          path: ./ocr-x86_64-apple-darwin

      - name: Upload arm64 Binary
        uses: actions/upload-artifact@v3
        with:
          name: ocr-aarch64-apple-darwin
          path: ./ocr-aarch64-apple-darwin