name: Build Swift Binary

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Swift
        run: |
          brew install swift

      - name: Build Swift Script
        run: |
          swiftc -target x86_64-apple-macos10.15 -o ocr-x86_64-apple-darwin main.swift
          swiftc -target arm64-apple-macos11 -o ocr-aarch64-apple-darwin main.swift

      - name: Set Permissions
        run: |
          chmod 755 ocr-x86_64-apple-darwin
          chmod 755 ocr-aarch64-apple-darwin
          ls -l ocr-x86_64-apple-darwin ocr-aarch64-apple-darwin

      - name: Create Archives
        run: |
          tar -czf ocr-x86_64-apple-darwin.tar.gz ocr-x86_64-apple-darwin
          tar -czf ocr-aarch64-apple-darwin.tar.gz ocr-aarch64-apple-darwin

      - name: Test
        run: ./ocr-x86_64-apple-darwin $(pwd)/test.jpg auto

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ocr-x86_64-apple-darwin
          path: ./ocr-x86_64-apple-darwin.tar.gz

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ocr-aarch64-apple-darwin
          path: ./ocr-aarch64-apple-darwin.tar.gz
